name: Build and Deploy

on:
  push:
    tags:
      - "v*.*.*" # Matches version tags like v1.0.0
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      version_tag:
        description: "Tag to deploy"
        required: true
        default: "v1.0.0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: shopping-cart

      - name: Configure Git
        run: |
          git config --global user.email "moize.ahsan@10pearls.com"
          git config --global user.name "MoizeAhsan-10P"

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: shopping-cart
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
